/** #48: human-only recording, field review, actual persistence and project JSON transfer.
 * Only 910×465 is recorded existing-fitting evidence. Height/services/source conflict are synthetic. */
import { chromium } from 'playwright';
import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
const base=process.env.ALZA_BASE_URL??'http://127.0.0.1:5348/';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
page.on('pageerror',e=>errors.push(String(e)));
const run=(name,args={})=>page.evaluate(([n,a])=>window.__alza.runTool(n,a),[name,args]);
try {
 await page.goto(base);await page.getByLabel('New project name').fill('Reused fitting #48');await page.getByRole('button',{name:'Create blank'}).click();await page.getByRole('button',{name:/^Products/}).click();
 const form=page.getByRole('form',{name:'New measured fitting'}),detail=page.getByRole('region',{name:'Selected request'});
 await form.getByRole('button',{name:'Open human measurements'}).click();assert.match(await form.textContent(),/Give the physical fitting a label/);
 await form.getByLabel('Physical fitting label').fill('Recorded existing vanity');await form.getByLabel('Physical identification notes').fill('Existing fitting: recorded 910 × 465 mm footprint. Manufacturer/model, height and connections not provided. Additional dimensions/services below are synthetic verification only.');await form.getByRole('button',{name:'Open human measurements'}).click();
 const req=(await run('list_product_requests')).requests.at(-1),brief=await run('get_product_brief',{requestId:req.id});assert.equal(brief.humanOnly,true);assert.equal((await run('submit_product_spec',{requestId:req.id,manufacturer:'Guessed',model:'Guessed',fields:{}})).ok,false);
 const record=async(key,value,status,datum,evidence,unknownDate=false)=>{
  const field=detail.locator(`[data-measurement-field="${key}"]`);if(!await field.evaluate(el=>el.open))await field.locator('summary').click();
  await field.getByLabel('Observation status').selectOption(status);await field.getByLabel('Observation value').fill(String(value));await field.getByLabel('Observation unit').selectOption('mm');await field.getByLabel('Physical datum').selectOption(datum);
  if(status==='published'){await field.getByLabel('Published source URL').fill('https://example.com/synthetic-vanity.pdf');await field.getByLabel('Published source locator').fill('p. 2, synthetic dimension table');}
  else {if(unknownDate)await field.getByLabel('Unknown date explanation').fill('Original measurement date not recorded');else await field.getByLabel('Measurement date',{exact:true}).fill('2026-10-03');await field.getByLabel('Measurement evidence / reference').fill(evidence);}
  await field.getByRole('button',{name:'Record observation'}).click();assert.equal(await field.getByRole('alert').count(),0,await field.textContent());return field;
 };
 await record('width',910,'measured','fixture-end','Recorded existing-fitting measurement: vanity footprint 910 × 465 mm',true);await record('depth',465,'measured','fixture-side','Recorded existing-fitting measurement: vanity footprint 910 × 465 mm',true);
 const review=async()=>{await detail.getByRole('button',{name:'Submit measurements for review'}).click();assert.match(await detail.textContent(),/Manufacturer.*unknown/);const rows=detail.locator('tbody tr[data-field]');for(let i=0;i<await rows.count();i++)await rows.nth(i).getByRole('button',{name:'Accept',exact:true}).click();await detail.getByRole('button',{name:'Accept product'}).click();assert.match(await detail.textContent(),/status accepted/);};
 await review();let p=(await run('get_product_library')).products.at(-1);assert.equal(p.fields.height.value,null);assert.equal(p.manufacturer,'');assert.equal(p.model,'');
 const wall=await run('add_wall',{ax:0,ay:0,bx:3,by:0,thickness:.1,height:2.4});await run('set_wall_side',{wallId:wall.id,side:'right',existing:{value:0,status:'measured'},frame:{value:0,status:'measured'},layers:[{kind:'tile',thickness:{value:0,status:'measured'}}]});
 const anchor={wallId:wall.id,side:'right',face:'existing',distance:.8,status:'proposed'};assert.equal((await run('place_product',{productId:p.id,...anchor})).ok,false);assert.equal((await run('get_model')).model.items.length,0);
 const card=page.locator(`[data-product="${p.id}"]`);await card.locator('summary').click();await card.getByRole('button',{name:'Record more measurements'}).click();
 const width=await record('width',900,'published','fixture-end');assert.match(await width.getByRole('table').textContent(),/910 mm.*measured.*900 mm.*published/s);await width.getByLabel('Working evidence for Overall width').selectOption('1');
 await record('height',840,'proposed','fixture-bottom','Synthetic test-only height; not an existing-fitting measurement');await record('wasteOffset',120,'measured','fixture-centreline','Synthetic test-only survey');await record('wasteHeight',550,'site-confirmed','finished-floor','Synthetic test-only human site confirmation');await record('service.waste.out',0,'proposed','finished-wall','Synthetic test-only wall connection');
 await review();p=(await run('get_product_library')).products.at(-1);assert.equal(p.fields.width.value,.910);assert.equal(p.fields.width.observations.at(-1).status,'published');
 const placed=await run('place_product',{productId:p.id,...anchor});assert.equal(placed.ok,true,placed.summary);
 assert.equal((await run('build_3d')).ok,true);
 const model=(await run('get_model')).model,item=model.items[0],sp=item.servicePoints[0];assert.equal(sp.status,'proposed');assert.equal(sp.axisEvidence.across.status,'measured');assert.equal(sp.axisEvidence.up.status,'site-confirmed');assert.equal(sp.axisEvidence.out.status,'proposed');assert.equal(item.productSpecification.fields.height.status,'proposed');
 await run('set_sheet_info',{project:'Reused fitting verification',site:'Test only',preparedBy:'Synthetic reviewer'});await run('set_diagram_view',{label:'Measured fitting',visible:['walls','fixtures','services-waste']});const view=await run('get_diagram_view',{includeSvg:true});assert.ok(view.spec.some(r=>r.property==='width'&&r.status==='measured'&&r.source.includes('Original measurement date')));assert.ok(view.spec.some(r=>r.property.includes('observation')&&r.status==='published'));assert.ok(view.spec.some(r=>r.property==='up from finished floor (mm)'&&r.status==='site-confirmed'));
 const exported=await run('export_diagram_view',{includeOutputs:true});assert.equal(exported.ok,true,exported.summary);assert.match(exported.specHtml,/Recorded existing-fitting measurement/);assert.match(exported.specHtml,/synthetic-vanity.pdf/);
 await page.reload();await page.locator('.project-card').filter({hasText:'Reused fitting #48'}).getByRole('button',{name:'Open',exact:true}).click();assert.equal((await run('get_product_library')).products.at(-1).fields.width.value,.910);assert.deepEqual((await run('get_model')).model.items[0].productSpecification,item.productSpecification);
 // Project JSON really downloads; import into a fresh browser context without product storage.
 await page.getByRole('button',{name:/^Projects/}).click();const downloadEvent=page.waitForEvent('download');await page.locator('.project-card').filter({hasText:'Reused fitting #48'}).getByRole('button',{name:'Export JSON'}).click();const raw=readFileSync(await (await downloadEvent).path(),'utf8');assert.deepEqual(JSON.parse(raw).model.items[0].productSpecification,item.productSpecification);
 const fresh=await browser.newContext(),fp=await fresh.newPage();await fp.goto(base);await fp.getByLabel('Import project JSON').setInputFiles({name:'reused.json',mimeType:'application/json',buffer:Buffer.from(raw)});await fp.getByRole('button',{name:'Import as new project'}).click();const frun=(name,args={})=>fp.evaluate(([n,a])=>window.__alza.runTool(n,a),[name,args]);assert.equal((await frun('get_product_library')).products.length,0);const imported=(await frun('get_model')).model;assert.deepEqual(imported.items[0].productSpecification,item.productSpecification);assert.deepEqual(imported.items[0].servicePoints[0].axisEvidence,sp.axisEvidence);await frun('set_diagram_view',{label:'Transferred evidence',visible:['walls','fixtures','services-waste']});const fv=await frun('get_diagram_view');assert.ok(fv.spec.some(r=>r.missing?.includes("product not in this browser's library")));assert.ok(fv.spec.some(r=>r.status==='measured'&&r.source?.includes('Recorded existing-fitting')));await fresh.close();assert.deepEqual(errors,[]);
 console.log('PASS: actual human measurement/review → incomplete envelope refusal → conflicting evidence selection → mixed-provenance placement/spec → reload → downloaded project import with source snapshot and absent-library advisory');
}finally{await browser.close();}
