/** #47: synthetic exact variants; genuine page requests/review/acceptance, agent tool submissions,
 * placement, project-owned selection, reload, JSON download/import into a browser with no catalogue,
 * then diagram/spec readback. example.com sources are synthetic, not researched product data. */
import { launch } from "./browser.mjs";
import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
const base = process.env.ALZA_BASE_URL ?? "http://127.0.0.1:5247/";
const browser = await launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
const page = await context.newPage();
const errors = [];
page.on("pageerror", e => errors.push(String(e)));
const source = { url: "https://example.com/synthetic-vanity.pdf", locator: "p. 2, variant table" };
const pub = value => ({ value, status: "published", sources: [source] });
const known = value => ({ state: "known", value, sources: [source] });
const make = finish => ({ manufacturer: "Synthetic Co", model: "Same Family 900", identity: { code: known(`V900-${finish}`), finish: known(finish), configuration: known("900 mm cabinet"), handedness: { state: "not-applicable", value: null, sources: [source] } }, componentsStatus: "documented", components: [{ name: "Waste", code: known("WASTE-32"), quantity: 1, provision: "separately-required", sources: [source] }], fields: { width: pub(.9), depth: pub(.45), height: pub(.6), mounting: pub("wall-hung"), benchHeight: pub(.85), wasteHeight: pub(.5), tapHoles: pub(1) } });
const run = (name, input = {}) => page.evaluate(([name, input]) => window.__alza.runTool(name, input), [name, input]);
try {
  await page.goto(base);
  await page.getByLabel("New project name").fill("Synthetic exact variants");
  await page.getByRole("button", { name: "Create blank" }).click();
  const wall = await run("add_wall", { ax: 0, ay: 0, bx: 3, by: 0, thickness: .1, height: 2.4 });
  assert.equal((await run("set_wall_side", { wallId: wall.id, side: "right", existing: { value: 0, status: "measured" }, layers: [] })).ok, true);
  await page.getByRole("button", { name: /^Products/ }).click();
  for (const finish of ["Chrome", "Brass"]) {
    const form = page.getByRole("form", { name: "New product request" });
    await form.getByLabel("Category").selectOption("vanity");
    await form.getByLabel("Brand", { exact: true }).fill("Synthetic Co");
    await form.getByLabel("Model", { exact: true }).fill("Same Family 900");
    for (const [key, label, value] of [["code", "Product code", `V900-${finish}`], ["finish", "Finish", finish], ["configuration", "Size / configuration", "900 mm cabinet"], ["handedness", "Handedness", null]]) {
      await form.getByLabel(`${label} status`).selectOption(value ? "known" : "not-applicable");
      if (value) await form.getByLabel(`${label} exact value`, { exact: true }).fill(value);
      await form.getByLabel(`${label} source URL`, { exact: true }).fill(source.url);
      await form.getByLabel(`${label} source locator`, { exact: true }).fill(source.locator);
    }
    if (await form.locator("details").getAttribute("open") === null) await form.getByText("Record component evidence", { exact: true }).click();
    for (const [label, value] of [["Component name", "Waste"], ["Component code", "WASTE-32"], ["Component quantity", "1"], ["Component source URL", source.url], ["Component source locator", source.locator]]) await form.getByLabel(label, { exact: true }).fill(value);
    await form.getByLabel("Component provision").selectOption("separately-required");
    await form.getByRole("button", { name: "Add component evidence" }).click();
    await form.getByRole("button", { name: "Open request" }).click();
    const requests = await run("list_product_requests");
    const req = requests.requests.at(-1);
    assert.equal(req.known.identity.finish.value, finish);
    assert.equal(req.known.components[0].code.value, "WASTE-32");
    const spec = make(finish);
    if (finish === "Brass") spec.identity.finish.alternatives = [{ value: "Chrome", source }];
    const result = await run("submit_product_spec", { requestId: req.id, ...spec });
    assert.equal(result.ok, true, result.summary);
    if (finish === "Brass") assert.ok(result.warnings.some(w => w.code === "identity_conflict"));
    const detail = page.getByRole("region", { name: "Selected request" });
    if (finish === "Brass") assert.match(await detail.textContent(), /conflicting with Brass/);
    assert.notEqual((await run("accept_product", { requestId: req.id })).ok, true);
    await detail.getByRole("button", { name: "Accept product" }).click();
    assert.match(await detail.getByRole("alert").last().textContent(), /Review every field/);
    const rows = detail.locator("tr[data-field]");
    for (let i = 0; i < await rows.count(); i++) await rows.nth(i).getByRole("button", { name: "Accept", exact: true }).click();
    await detail.getByRole("button", { name: "Accept product" }).click();
    assert.match(await detail.textContent(), /status accepted/);
    const lib = await run("get_product_library");
    const product = lib.products.at(-1);
    assert.equal(product.identity.finish.value, finish);
    assert.equal(product.components[0].provision, "separately-required");
    const placed = await run("place_product", { productId: product.id, wallId: wall.id, side: "right", face: "existing", distance: finish === "Chrome" ? .7 : 2.2, status: "proposed" });
    assert.equal(placed.ok, true, placed.summary);
    assert.equal((await run("get_rough_in", { itemId: placed.id })).fixtures[0].selectionStatus, "unknown");
  }
  const lib = await run("get_product_library");
  assert.equal(lib.products.length, 2);
  assert.notEqual(lib.products[0].id, lib.products[1].id);
  await page.getByRole("region", { name: "Library" }).locator("details").first().locator("summary").click();
  await page.screenshot({ path: "/tmp/layout-bench-47-products.png", fullPage: true });
  await page.getByRole("button", { name: "Back to plan" }).click();
  const items = await page.evaluate(() => window.__alza.store.getState().model.items);
  await page.evaluate(id => window.__alza.actions.selectItem(id), items[0].id);
  const selection = page.getByLabel("Project selection", { exact: true });
  assert.equal(await selection.inputValue(), "unknown");
  await selection.selectOption("purchased");
  assert.equal((await run("set_fixture_selection", { itemId: items[1].id, status: "reused" })).ok, true);
  assert.match(await page.getByRole("region", { name: "Fixture set-out" }).textContent(), /V900-Chrome.*Chrome.*separately-required/s);
  await run("set_sheet_info", { project: "Synthetic variant demonstration", site: "Synthetic bathroom", preparedBy: "E2E" });
  const view = await run("set_diagram_view", { label: "Synthetic fit-out", visible: ["walls", "fixtures"] });
  assert.equal(view.ok, true, view.summary);
  const beforeReload = await run("get_diagram_view", { includeSvg: true });
  assert.match(beforeReload.svg, /V900-Chrome/);
  assert.match(beforeReload.svg, /V900-Brass/);
  const rows = beforeReload.spec;
  assert.ok(rows.some(r => r.property === "Finish" && r.value === "Chrome"));
  assert.ok(rows.some(r => r.property === "component 1" && /WASTE-32.*separately-required/.test(r.value)));
  await page.reload();
  await page.locator(".project-card").filter({ hasText: "Synthetic exact variants" }).getByRole("button", { name: "Open", exact: true }).click();
  const restored = await page.evaluate(() => window.__alza.store.getState().model.items);
  assert.deepEqual(restored.map(i => [i.productIdentity.identity.finish.value, i.selectionStatus]), [["Chrome", "purchased"], ["Brass", "reused"]]);
  await page.getByRole("button", { name: "Projects", exact: true }).click();
  const downloadPromise = page.waitForEvent("download");
  await page.locator(".project-card").filter({ hasText: "Synthetic exact variants" }).getByRole("button", { name: "Export JSON" }).click();
  const download = await downloadPromise;
  const raw = readFileSync(await download.path(), "utf8");
  const fresh = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const freshPage = await fresh.newPage();
  freshPage.on("pageerror", e => errors.push(String(e)));
  await freshPage.goto(base);
  await freshPage.getByLabel("Import project JSON").setInputFiles({ name: "synthetic-variants.json", mimeType: "application/json", buffer: Buffer.from(raw) });
  await freshPage.getByRole("button", { name: "Import as new project" }).click();
  const runFresh = (name, args = {}) => freshPage.evaluate(([name, args]) => window.__alza.runTool(name, args), [name, args]);
  assert.equal((await runFresh("get_product_library")).products.length, 0);
  const imported = await freshPage.evaluate(() => window.__alza.store.getState().model.items);
  assert.deepEqual(imported.map(i => [i.productIdentity.identity.code.value, i.selectionStatus]), [["V900-Chrome", "purchased"], ["V900-Brass", "reused"]]);
  assert.equal((await runFresh("set_diagram_view", { label: "Imported synthetic fit-out", visible: ["walls", "fixtures"] })).ok, true);
  const readback = await runFresh("get_diagram_view", { includeSvg: true });
  const importedRows = readback.spec;
  assert.ok(importedRows.some(r => r.property === "Finish" && r.value === "Brass"));
  assert.ok(importedRows.some(r => r.property === "component 1" && /WASTE-32.*separately-required/.test(r.value)));
  assert.match(readback.svg, /V900-Brass/);
  assert.deepEqual(errors, []);
  await fresh.close();
  console.log("PASS #47: genuine UI exact requests + component evidence, conflicting research review/acceptance, distinct placement, UI/tool selection, reload, project export/import in fresh browser, exact diagram/spec identity");
} finally { await browser.close(); }
