/** #48 reviewer regressions: synthetic human toilet ranges; no real fitting claims. */
import {chromium} from 'playwright';
import {strict as assert} from 'node:assert';
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];
page.on('pageerror',e=>errors.push(String(e)));const run=(name,args={})=>page.evaluate(([n,a])=>window.__alza.runTool(n,a),[name,args]);
try{
 await page.goto(process.env.ALZA_BASE_URL??'http://127.0.0.1:5348/');await page.getByLabel('New project name').fill('Synthetic measured ranges');await page.getByRole('button',{name:'Create blank'}).click();await page.getByRole('button',{name:/^Products/}).click();
 const form=page.getByRole('form',{name:'New measured fitting'}),detail=page.getByRole('region',{name:'Selected request'});await form.getByLabel('Measured category').selectOption('toilet');await form.getByLabel('Physical fitting label').fill('Synthetic measured pan');await form.getByRole('button',{name:'Open human measurements'}).click();
 const record=async(key,value,datum,status='measured',evidence='Synthetic human ruler evidence')=>{
  const field=detail.locator(`[data-measurement-field="${key}"]`);if(!await field.evaluate(el=>el.open))await field.locator('summary').click();await field.getByLabel('Observation status').selectOption(status);
  if(key==='trap')await field.getByLabel('Observation value').selectOption(value);else await field.getByLabel('Observation value').fill(String(value));await field.getByLabel('Observation unit').selectOption(key==='trap'?'choice':'mm');if(datum)await field.getByLabel('Physical datum').selectOption(datum);await field.getByLabel('Measurement date',{exact:true}).fill('2026-10-03');await field.getByLabel('Measurement evidence / reference').fill(evidence);await field.getByRole('button',{name:'Record observation'}).click();assert.equal(await field.getByRole('alert').count(),0,await field.textContent());
 };
 for(const [key,value,datum]of[['width',400,'fixture-end'],['depth',650,'fixture-side'],['height',800,'fixture-bottom'],['trap','S'],['sTrapSetoutMin',300,'finished-wall'],['sTrapSetoutMax',100,'finished-wall'],['service.waste-s.across',0,'fixture-centreline'],['service.waste-s.up',0,'finished-floor']])await record(key,value,datum);
 const req=(await run('list_product_requests')).requests.at(-1);await detail.getByRole('button',{name:'Submit measurements for review'}).click();assert.match(await detail.getByRole('alert').last().textContent(),/minimum exceeds sTrapSetoutMax/);assert.equal((await run('list_product_requests')).requests.at(-1).status,'open');assert.equal((await run('get_product_library')).products.length,0);
 // Differing physical datums stay unresolved and retain evidence; never order these numbers.
 await record('sTrapSetoutMax',100,'frame','proposed','Synthetic maximum from frame; no conversion supplied');await detail.getByRole('button',{name:'Submit measurements for review'}).click();const brief=await run('get_product_brief',{requestId:req.id});assert.ok(brief.previousSubmission.warnings.some(w=>w.code==='range_datum_mismatch'));assert.ok(!brief.previousSubmission.warnings.some(w=>w.code==='range_reversed'));
 const accept=async()=>{const rows=detail.locator('tbody tr[data-field]');for(let i=0;i<await rows.count();i++)await rows.nth(i).getByRole('button',{name:'Accept',exact:true}).click();await detail.getByRole('button',{name:'Accept product'}).click();assert.match(await detail.textContent(),/status accepted/);};await accept();const unresolved=(await run('get_product_library')).products.at(-1);assert.equal(unresolved.roughIn.find(p=>p.id==='waste-s').out.min,undefined);assert.equal(unresolved.roughIn.find(p=>p.id==='waste-s').out.maxEvidence.reference,'frame');
 const card=page.locator(`[data-product="${unresolved.id}"]`);await card.locator('summary').click();await card.getByRole('button',{name:'Record more measurements'}).click();await record('sTrapSetoutMin',100,'finished-wall','measured','Synthetic minimum ruler measurement');await record('sTrapSetoutMax',300,'finished-wall','proposed','Synthetic maximum proposed allowance');await detail.getByRole('button',{name:'Submit measurements for review'}).click();await accept();const p=(await run('get_product_library')).products.at(-1);
 const wall=await run('add_wall',{ax:0,ay:0,bx:3,by:0,thickness:.1,height:2.4});await run('set_wall_side',{wallId:wall.id,side:'right',existing:{value:0,status:'measured'},frame:{value:0,status:'measured'},layers:[{kind:'tile',thickness:{value:0,status:'measured'}}]});const placed=await run('place_product',{productId:p.id,wallId:wall.id,side:'right',face:'existing',distance:1,status:'proposed'});assert.equal(placed.ok,true,placed.summary);await run('set_sheet_info',{project:'Synthetic range',site:'Test only',preparedBy:'Human test reviewer'});await run('set_diagram_view',{label:'Synthetic range evidence',visible:['walls','fixtures','services-waste']});const view=await run('get_diagram_view');const range=view.spec.find(r=>r.property==='out from finished face (mm)');assert.equal(range.value,'100–300');assert.equal(range.status,'proposed');assert.match(range.source,/Synthetic minimum ruler measurement/);assert.match(range.source,/Synthetic maximum proposed allowance/);assert.ok(view.spec.some(r=>r.property==='out source evidence'&&r.status==='measured'&&r.datum==='finished-wall'));assert.ok(view.spec.some(r=>r.property==='outMax source evidence'&&r.status==='proposed'&&r.datum==='finished-wall'));const exported=await run('export_diagram_view',{includeOutputs:true});assert.equal(exported.ok,true,exported.summary);assert.match(exported.specHtml,/Synthetic maximum proposed allowance/);assert.deepEqual(errors,[]);
 console.log('PASS: reversed comparable human range blocked; unlike datums retained unresolved; corrected mixed-status range reviewed/placed/exported with both endpoint provenance records');
}finally{await browser.close();}
