/**
 * The shipped Bathroom Concept sample's trade sheets, the ones the stage pack does not cover: the
 * A-01 floor plan (an unissued preview with its findings), the floor tiling sheet, one wall tiling
 * sheet per tiled wall side, and the heating review. Each is the same render the app's Sheets,
 * Tiling and Heating panels use. Nothing in the model is edited; the script fails if it changed.
 *
 *   npm run sample-sheets
 *
 * Output: shots/sample-sheets/ and shots/sample-sheets/README.md
 */

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { WallSideName } from "../src/model/types";

const OUT = resolve(fileURLToPath(new URL("../shots/sample-sheets", import.meta.url)));

// The store saves to localStorage on every change; give it a throwaway one so the sample opens here
// exactly as it does in the browser.
const mem = new Map<string, string>();
(globalThis as { localStorage?: unknown }).localStorage = {
  getItem: (k: string) => mem.get(k) ?? null,
  setItem: (k: string, v: string) => void mem.set(k, String(v)),
  removeItem: (k: string) => void mem.delete(k),
  clear: () => mem.clear(),
  key: (i: number) => [...mem.keys()][i] ?? null,
  get length() { return mem.size; },
};

const { store, initializeProjects, projects } = await import("../src/model/store");
const { DEMO_ID } = await import("../src/model/projects");
const { checkSheet } = await import("../src/sheets/check");
const { renderFloorPlan } = await import("../src/sheets/floorPlan");
const { renderFloorTilingSheet } = await import("../src/sheets/floorTiling");
const { renderTilingSheet } = await import("../src/sheets/tiling");
const { renderHeatingReview } = await import("../src/sheets/heating");

initializeProjects();
const opened = projects.open(DEMO_ID);
if (!opened.ok) throw new Error(`Could not open the sample: ${opened.summary}`);
const model = store.getState().model;
const before = JSON.stringify(model);

const files: { name: string; title: string; body: string }[] = [];
const findings = checkSheet(model, "floor-plan");
const blocking = findings.filter((f) => f.severity === "blocking");
if (blocking.length) throw new Error(`The sample's floor plan is blocked: ${blocking.map((f) => f.message).join(" ")}`);
files.push({ name: "A-01-floor-plan.svg", title: "A-01 floor plan (unissued preview)", body: renderFloorPlan(model, { sheet: "floor-plan", findings, revision: null }) });
for (const room of model.rooms) {
  if (room.floorTiling) files.push({ name: `floor-tiling-${room.id}.svg`, title: `Floor tiling: ${room.label}`, body: renderFloorTilingSheet(model, room) });
  if (room.heating) files.push({ name: `heating-${room.id}.html`, title: `Heating review: ${room.label}`, body: `<!doctype html><meta charset="utf-8"><title>Heating review: ${room.label}</title>${renderHeatingReview(room)}` });
}
for (const w of model.walls) {
  for (const side of Object.keys(w.tiling ?? {}) as WallSideName[]) {
    files.push({ name: `wall-tiling-${w.id}-${side}.svg`, title: `Wall tiling: ${w.id} (${side} side)`, body: renderTilingSheet(model, w.id, side) });
  }
}
if (JSON.stringify(store.getState().model) !== before) throw new Error("The model changed while rendering sheets. Nothing was written.");

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
for (const f of files) writeFileSync(join(OUT, f.name), f.body);
const md = [
  `# Trade sheets: ${model.name}`,
  "",
  "Generated by `npm run sample-sheets` from the shipped sample, with the same renders the app's Sheets, Tiling and Heating panels use. The per-stage plans, elevations and specifications are in [the stage pack](../stage-pack/README.md).",
  "",
  `Floor plan findings: ${findings.length} advisory, none blocking.`,
  "",
  ...files.map((f) => `- [${f.title}](${f.name})`),
  "",
];
writeFileSync(join(OUT, "README.md"), md.join("\n"));
console.log(`Wrote ${files.length} sheet(s) to ${OUT}`);
